# Generated by Django 5.1.4 on 2025-01-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('customer_inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('customer_kpp', models.CharField(max_length=255, verbose_name='КПП')),
                ('customer_legal_address', models.CharField(max_length=255, verbose_name='Юр. адрес')),
                ('customer_postal_address', models.CharField(max_length=255, verbose_name='Почтовый адрес')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('is_organization', models.BooleanField(verbose_name='Юр. лицо')),
                ('is_person', models.BooleanField(verbose_name='Физ. лицо')),
                ('customer_code_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Вышестоящий контрагент')),
            ],
            options={
                'verbose_name': 'Справочники контрагентов',
                'verbose_name_plural': 'Справочник контрагентов',
            },
        ),
    ]
