# Generated by Django 5.1.4 on 2025-01-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Справочник контрагентов', 'verbose_name_plural': 'Справочники контрагентов'},
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=255, verbose_name='Наименование лота')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Начальная стоимость')),
                ('currency_code', models.CharField(choices=[('R', 'RUB'), ('U', 'USD'), ('E', 'EUR')], max_length=3, verbose_name='Валюта')),
                ('nbs_rate', models.CharField(choices=[('N', 'Без НДС'), ('OE', '18%'), ('TZ', '20%')], max_length=2, verbose_name='Код НДС')),
                ('place_delivery', models.CharField(max_length=255, verbose_name='Грузополучатель')),
                ('date_delivery', models.DateField(verbose_name='Дата доставки')),
                ('customer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Код контрагента')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
            },
        ),
    ]
