# Generated by Django 5.1.4 on 2025-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=255, verbose_name='Код контрагента'),
        ),
    ]
